# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: libp2p
types:
  libp2p:index:KeyType:
    type: string
    enum: 
      - name: RSA
        value: RSA
      - name: ED25519
        value: ED25519
      - name: SECP256K1
        value: SECP256K1
      - name: ECDSA
        value: ECDSA
resources:
  libp2p:index:Key:
    isComponent: true
    inputProperties:
      type:
        type: enum
        $ref: "#/types/libp2p:index:KeyType"
        description: Type of the key to generate one of RSA, ED25519, SECP256K1, ECDSA
        replaceOnChanges: true
      bits:
        type: integer
        description: Siye of the key (Only for RSA key)
        replaceOnChanges: true
    requiredInputs:
      - type
    properties:
      peerId:
        type: string
        description: Peer ID
      private:
        type: string
        description: Marshalled private key
        secret: true
      public:
        type: string
        description: Marshalled public key
    required:
      - peerId
      - private
      - public
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/LuxChanLu/pulumi-libp2p/sdk/go/libp2p
  nodejs:
    dependencies:
      "@pulumi/pulumi": "^3.45.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
