# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .key import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "libp2p",
  "mod": "index",
  "fqn": "pulumi_libp2p",
  "classes": {
   "libp2p:index:Key": "Key"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "libp2p",
  "token": "pulumi:providers:libp2p",
  "fqn": "pulumi_libp2p",
  "class": "Provider"
 }
]
"""
)
