# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'KeyType',
]


class KeyType(str, Enum):
    RSA = "RSA"
    ED25519 = "ED25519"
    SECP256_K1 = "SECP256K1"
    ECDSA = "ECDSA"
