// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const KeyType = {
    RSA: "RSA",
    ED25519: "ED25519",
    SECP256K1: "SECP256K1",
    ECDSA: "ECDSA",
} as const;

export type KeyType = (typeof KeyType)[keyof typeof KeyType];
